name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 2.0.0
homepage: https://github.com/jzoom/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view:
    git:
      url: git@github.com:noveleven/transformer_page_view.git
      ref: master
  
  flutter_page_indicator:
    git:
      url: git@github.com:noveleven/flutter_page_indicator.git
      ref: master

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.1.4 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
